import "~/styles/globals.css";

import type { Metadata } from "next/types";

export const metadata: Metadata = {
  title: "T3 Auth",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return children
}
